# Project Configuration File

# Basic project information
project:
  name: "data-engineering-project"
  version: "1.0.0"
  description: "Data engineering pipeline configuration"
  author: "Your Name"

# Environment settings
environment:
  # Production, Development, Staging, etc.
  env_type: "development"
  log_level: "INFO"

# Database connections
databases:
  # Source database configuration
  source:
    type: "postgresql"
    host: "localhost"
    port: 5432
    database: "source_db"
    username: "${SOURCE_DB_USER}"  # Using environment variable
    password: "${SOURCE_DB_PASS}"  # Using environment variable
    
  # Target data warehouse configuration
  warehouse:
    type: "snowflake"
    account: "your_account"
    warehouse: "compute_wh"
    database: "target_db"
    schema: "public"
    role: "reporter"
    username: "${DW_USER}"
    password: "${DW_PASS}"

# Data processing settings
processing:
  # Batch processing configurations
  batch:
    max_records: 10000
    parallel_jobs: 4
    timeout_seconds: 3600
  
  # Data validation rules
  validation:
    enable_checks: true
    fail_on_error: false
    
# Storage configurations
storage:
  # Local storage settings
  local:
    input_path: "./data/input"
    output_path: "./data/output"
    temp_path: "./data/temp"
    
  # Cloud storage settings
  cloud:
    provider: "aws"
    bucket: "my-data-bucket"
    region: "us-east-1"
    
# Pipeline scheduling
schedule:
  enabled: true
  cron: "0 0 * * *"  # Daily at midnight
  timezone: "UTC"

# Monitoring and alerting
monitoring:
  enable_metrics: true
  alert_email: "alerts@company.com"
  threshold_values:
    max_latency_seconds: 300
    error_rate_threshold: 0.01

# Security settings
security:
  encryption_enabled: true
  ssl_verify: true
  api_rate_limit: 1000